
server:
  port: 8880
spring:
  application:
    name: ada-recommend-provider

mybatis:
  mapper-locations: classpath*:/com/ada/recommend/dao/mapper/*.xml
  type-aliases-package: classpath*:com.ada.recommend.dao.dto

# 加解密根密码
jasypt:
  encryptor:
    password: qqqq #根密码

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
