
# Spring 相关
spring:
  cloud:
    consul:
      host: 10.19.1.104
      port: 8500
      discovery:
        register: true
        serviceName: ${spring.application.name}
        preferIpAddress: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 10s
        health-check-critical-timeout: 30s #健康检查失败多长时间后，取消注册
        health-check-tls-skip-verify: true
    sentinel:
      transport:
        dashboard: dev.sentinel.ada-pz.com:80
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: adadevuser
    password: adadevuser123
    url: jdbc:mysql://10.19.1.102:3306/adadevdb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

### Ribbon 配置
ribbon:
  # http建立socket超时时间,毫秒
  ConnectTimeout: 2000
  # http读取响应socket超时时间
  ReadTimeout: 5000
  # 同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 0
  # 重试负载均衡其他的实例最大重试次数,不包括首次server
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试，POST请求注意多次提交错误。
  # 默认false，设定为false的话，只有get请求会重试
  OkToRetryOnAllOperations: false
  eager-load:
    enabled: true
    clients: ada-recommend-provider